---
  openapi: "3.1.0"
  info: 
    title: "Streams"
    version: "1.0.0"
    description: "Programatically control Airbyte Cloud, OSS & Enterprise."
  servers: 
    - 
      url: "https://api.airbyte.com/v1"
      description: "Airbyte API v1"
  paths: 
    /streams: 
      get: 
        tags: 
          - "Streams"
        responses: 
          200: 
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/StreamPropertiesResponse"
            description: "Get the available streams properties for a source/destination pair."
          400: 
            description: "Required parameters are missing"
          403: 
            description: "Not allowed"
          404: 
            description: "Not found"
        operationId: "getStreamProperties"
        summary: "Get stream properties"
        x-use-speakeasy-middleware: true
        parameters: 
          - 
            name: "sourceId"
            description: "ID of the source"
            schema: 
              format: "UUID"
              type: "string"
            in: "query"
            required: true
          - 
            name: "destinationId"
            description: "ID of the destination"
            schema: 
              format: "UUID"
              type: "string"
            in: "query"
            required: true
          - 
            name: "ignoreCache"
            description: "If true pull the latest schema from the source, else pull from cache (default false)"
            schema: 
              type: "boolean"
              default: false
            in: "query"
            required: false
  components: 
    responses: 
      InitiateOauthResponse: 
        content: 
          application/json: {}
        description: "Response from the initiate OAuth call should be an object with a single property which will be the `redirect_url`. If a user is redirected to this URL, they'll be prompted by the identity provider to authenticate."
    schemas: 
      RedirectUrlResponse: 
        title: "Root Type for RedirectUrlResponse"
        description: ""
        type: "object"
        properties: 
          redirectUrl: 
            format: "url"
            type: "string"
        example: 
          redirectUrl: "https://airbyte.portal.speakeasyapi.dev?speakeasyAccessToken=eydas.ad45.1234"
      JobResponse: 
        title: "Root Type for JobResponse"
        description: "Provides details of a single job."
        required: 
          - "jobId"
          - "status"
          - "jobType"
          - "startTime"
          - "connectionId"
        type: "object"
        properties: 
          jobId: 
            format: "int64"
            type: "integer"
          status: 
            $ref: "#/components/schemas/JobStatusEnum"
          jobType: 
            $ref: "#/components/schemas/JobTypeEnum"
          startTime: 
            type: "string"
          connectionId: 
            format: "UUID"
            type: "string"
          lastUpdatedAt: 
            type: "string"
          duration: 
            description: "Duration of a sync in ISO_8601 format"
            type: "string"
          bytesSynced: 
            format: "int64"
            type: "integer"
          rowsSynced: 
            format: "int64"
            type: "integer"
        example: 
          id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          status: "running"
          jobType: "sync"
          startTime: "2023-03-25T01:30:50Z"
          duration: "PT8H6M12S"
      JobsResponse: 
        title: "Root Type for JobsResponse"
        description: ""
        required: 
          - "data"
        type: "object"
        properties: 
          previous: 
            type: "string"
          next: 
            type: "string"
          data: 
            type: "array"
            items: 
              $ref: "#/components/schemas/JobResponse"
        example: 
          next: "https://api.airbyte.com/v1/jobs?limit=5&offset=10"
          previous: "https://api.airbyte.com/v1/jobs?limit=5&offset=0"
          data: 
            - 
              id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
              status: "running"
              jobType: "sync"
              startTime: "2023-03-25T01:30:50Z"
      ConnectionCreateRequest: 
        required: 
          - "sourceId"
          - "destinationId"
        type: "object"
        properties: 
          name: 
            description: "Optional name of the connection"
            type: "string"
          sourceId: 
            format: "uuid"
            type: "string"
          destinationId: 
            format: "uuid"
            type: "string"
          configurations: 
            $ref: "#/components/schemas/StreamConfigurations"
          schedule: 
            $ref: "#/components/schemas/ConnectionSchedule"
          dataResidency: 
            $ref: "#/components/schemas/GeographyEnum"
          namespaceDefinition: 
            $ref: "#/components/schemas/NamespaceDefinitionEnum"
          namespaceFormat: 
            type: "string"
            description: "Used when namespaceDefinition is 'custom_format'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'."
            default: null
            example: "${SOURCE_NAMESPACE}"
          prefix: 
            type: "string"
            description: "Prefix that will be prepended to the name of each stream when it is written to the destination (ex. “airbyte_” causes “projects” => “airbyte_projects”)."
          nonBreakingSchemaUpdatesBehavior: 
            $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnum"
          status: 
            $ref: "#/components/schemas/ConnectionStatusEnum"
        x-speakeasy-entity: "Connection"
        x-speakeasy-param-suppress-computed-diff: true
      ConnectionPatchRequest: 
        type: "object"
        properties: 
          name: 
            description: "Optional name of the connection"
            type: "string"
          configurations: 
            $ref: "#/components/schemas/StreamConfigurations"
          schedule: 
            $ref: "#/components/schemas/ConnectionSchedule"
          dataResidency: 
            $ref: "#/components/schemas/GeographyEnumNoDefault"
          namespaceDefinition: 
            $ref: "#/components/schemas/NamespaceDefinitionEnumNoDefault"
          namespaceFormat: 
            type: "string"
            description: "Used when namespaceDefinition is 'custom_format'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'."
            default: null
            example: "${SOURCE_NAMESPACE}"
          prefix: 
            type: "string"
            description: "Prefix that will be prepended to the name of each stream when it is written to the destination (ex. “airbyte_” causes “projects” => “airbyte_projects”)."
          nonBreakingSchemaUpdatesBehavior: 
            $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnumNoDefault"
          status: 
            $ref: "#/components/schemas/ConnectionStatusEnum"
        x-speakeasy-entity: "Connection"
        x-speakeasy-param-suppress-computed-diff: true
      JobCreateRequest: 
        title: "Root Type for JobCreate"
        description: "Creates a new Job from the configuration provided in the request body."
        required: 
          - "jobType"
          - "connectionId"
        type: "object"
        properties: 
          connectionId: 
            format: "UUID"
            type: "string"
          jobType: 
            $ref: "#/components/schemas/JobTypeEnum"
        example: 
          connectionId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          jobType: "sync"
      JobStatusEnum: 
        enum: 
          - "pending"
          - "running"
          - "incomplete"
          - "failed"
          - "succeeded"
          - "cancelled"
        type: "string"
      JobTypeEnum: 
        description: "Enum that describes the different types of jobs that the platform runs."
        enum: 
          - "sync"
          - "reset"
        type: "string"
      SourceCreateRequest: 
        required: 
          - "name"
          - "workspaceId"
          - "configuration"
        type: "object"
        properties: 
          name: 
            type: "string"
          workspaceId: 
            format: "uuid"
            type: "string"
          configuration: 
            $ref: "#/components/schemas/SourceConfiguration"
          secretId: 
            description: "Optional secretID obtained through the public API OAuth redirect flow."
            type: "string"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Source"
        x-speakeasy-param-suppress-computed-diff: true
      SourcePutRequest: 
        required: 
          - "name"
          - "configuration"
        type: "object"
        properties: 
          name: 
            type: "string"
          configuration: 
            $ref: "#/components/schemas/SourceConfiguration"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Source"
        x-speakeasy-param-suppress-computed-diff: true
      SourcePatchRequest: 
        type: "object"
        properties: 
          name: 
            type: "string"
            example: "My source"
          workspaceId: 
            format: "uuid"
            type: "string"
          configuration: 
            $ref: "#/components/schemas/SourceConfiguration"
          secretId: 
            description: "Optional secretID obtained through the public API OAuth redirect flow."
            type: "string"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Source"
        x-speakeasy-param-suppress-computed-diff: true
      OAuthInputConfiguration: 
        description: "Arbitrary vars to pass for OAuth depending on what the source/destination spec requires."
        type: "object"
        example: 
          host: "test.snowflake.com"
      ConnectionResponse: 
        title: "Root Type for ConnectionResponse"
        description: "Provides details of a single connection."
        type: "object"
        required: 
          - "connectionId"
          - "name"
          - "sourceId"
          - "destinationId"
          - "workspaceId"
          - "status"
          - "schedule"
          - "dataResidency"
          - "configurations"
        properties: 
          connectionId: 
            format: "UUID"
            type: "string"
          name: 
            type: "string"
          sourceId: 
            format: "UUID"
            type: "string"
          destinationId: 
            format: "UUID"
            type: "string"
          workspaceId: 
            format: "UUID"
            type: "string"
          status: 
            $ref: "#/components/schemas/ConnectionStatusEnum"
          schedule: 
            $ref: "#/components/schemas/ConnectionScheduleResponse"
          dataResidency: 
            $ref: "#/components/schemas/GeographyEnum"
          nonBreakingSchemaUpdatesBehavior: 
            $ref: "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnum"
          namespaceDefinition: 
            $ref: "#/components/schemas/NamespaceDefinitionEnum"
          namespaceFormat: 
            type: "string"
          prefix: 
            type: "string"
          configurations: 
            $ref: "#/components/schemas/StreamConfigurations"
        x-speakeasy-entity: "Connection"
        x-speakeasy-param-suppress-computed-diff: true
      ConnectionSchedule: 
        description: "schedule for when the the connection should run, per the schedule type"
        type: "object"
        required: 
          - "scheduleType"
        properties: 
          scheduleType: 
            $ref: "#/components/schemas/ScheduleTypeEnum"
          cronExpression: 
            type: "string"
      ScheduleTypeEnum: 
        type: "string"
        enum: 
          - "manual"
          - "cron"
      ConnectionScheduleResponse: 
        description: "schedule for when the the connection should run, per the schedule type"
        type: "object"
        required: 
          - "scheduleType"
        properties: 
          scheduleType: 
            $ref: "#/components/schemas/ScheduleTypeWithBasicEnum"
          cronExpression: 
            type: "string"
          basicTiming: 
            type: "string"
      ScheduleTypeWithBasicEnum: 
        type: "string"
        enum: 
          - "manual"
          - "cron"
          - "basic"
      GeographyEnum: 
        type: "string"
        enum: 
          - "auto"
          - "us"
          - "eu"
        default: "auto"
      GeographyEnumNoDefault: 
        type: "string"
        enum: 
          - "auto"
          - "us"
          - "eu"
      ConnectionStatusEnum: 
        type: "string"
        enum: 
          - "active"
          - "inactive"
          - "deprecated"
      NamespaceDefinitionEnum: 
        type: "string"
        description: "Define the location where the data will be stored in the destination"
        enum: 
          - "source"
          - "destination"
          - "custom_format"
        default: "destination"
      NonBreakingSchemaUpdatesBehaviorEnum: 
        type: "string"
        description: "Set how Airbyte handles syncs when it detects a non-breaking schema change in the source"
        enum: 
          - "ignore"
          - "disable_connection"
          - "propagate_columns"
          - "propagate_fully"
        default: "ignore"
      NamespaceDefinitionEnumNoDefault: 
        type: "string"
        description: "Define the location where the data will be stored in the destination"
        enum: 
          - "source"
          - "destination"
          - "custom_format"
      NonBreakingSchemaUpdatesBehaviorEnumNoDefault: 
        type: "string"
        description: "Set how Airbyte handles syncs when it detects a non-breaking schema change in the source"
        enum: 
          - "ignore"
          - "disable_connection"
          - "propagate_columns"
          - "propagate_fully"
      DestinationResponse: 
        title: "Root Type for DestinationResponse"
        description: "Provides details of a single destination."
        type: "object"
        required: 
          - "destinationId"
          - "name"
          - "destinationType"
          - "workspaceId"
          - "configuration"
        properties: 
          destinationId: 
            format: "UUID"
            type: "string"
          name: 
            type: "string"
          destinationType: 
            type: "string"
          workspaceId: 
            format: "UUID"
            type: "string"
          configuration: 
            $ref: "#/components/schemas/DestinationConfiguration"
        example: 
          destinationId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          name: "Analytics Team Postgres"
          destinationType: "postgres"
          workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      SourceResponse: 
        title: "Root Type for SourceResponse"
        description: "Provides details of a single source."
        type: "object"
        required: 
          - "sourceId"
          - "name"
          - "sourceType"
          - "workspaceId"
          - "configuration"
        properties: 
          sourceId: 
            format: "UUID"
            type: "string"
          name: 
            type: "string"
          sourceType: 
            type: "string"
          workspaceId: 
            format: "UUID"
            type: "string"
          configuration: 
            $ref: "#/components/schemas/SourceConfiguration"
        example: 
          sourceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
          name: "Analytics Team Postgres"
          sourceType: "postgres"
          workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      DestinationCreateRequest: 
        required: 
          - "name"
          - "workspaceId"
          - "configuration"
        type: "object"
        properties: 
          name: 
            type: "string"
          workspaceId: 
            format: "uuid"
            type: "string"
          configuration: 
            $ref: "#/components/schemas/DestinationConfiguration"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Destination"
        x-speakeasy-param-suppress-computed-diff: true
      DestinationPatchRequest: 
        type: "object"
        properties: 
          name: 
            type: "string"
          configuration: 
            $ref: "#/components/schemas/DestinationConfiguration"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Destination"
        x-speakeasy-param-suppress-computed-diff: true
      DestinationPutRequest: 
        required: 
          - "name"
          - "configuration"
        type: "object"
        properties: 
          name: 
            type: "string"
          configuration: 
            $ref: "#/components/schemas/DestinationConfiguration"
        x-implements: "io.airbyte.public_api.server.helpers.ConfigurableActor"
        x-speakeasy-entity: "Destination"
        x-speakeasy-param-suppress-computed-diff: true
      WorkspaceCreateRequest: 
        required: 
          - "name"
        type: "object"
        properties: 
          name: 
            description: "Name of the workspace"
            type: "string"
        x-speakeasy-entity: "Workspace"
        x-speakeasy-param-suppress-computed-diff: true
      WorkspaceUpdateRequest: 
        required: 
          - "name"
        type: "object"
        properties: 
          name: 
            description: "Name of the workspace"
            type: "string"
        x-speakeasy-entity: "Workspace"
        x-speakeasy-param-suppress-computed-diff: true
      WorkspaceResponse: 
        title: "Root Type for WorkspaceResponse"
        description: "Provides details of a single workspace."
        type: "object"
        required: 
          - "workspaceId"
          - "name"
          - "dataResidency"
        properties: 
          workspaceId: 
            format: "UUID"
            type: "string"
          name: 
            type: "string"
          dataResidency: 
            $ref: "#/components/schemas/GeographyEnum"
        x-speakeasy-entity: "Workspace"
        x-speakeasy-param-suppress-computed-diff: true
      ConnectionsResponse: 
        title: "Root Type for ConnectionsResponse"
        description: ""
        required: 
          - "data"
        type: "object"
        properties: 
          previous: 
            type: "string"
          next: 
            type: "string"
          data: 
            type: "array"
            items: 
              $ref: "#/components/schemas/ConnectionResponse"
            default: []
        example: 
          next: "https://api.airbyte.com/v1/connections?limit=5&offset=10"
          previous: "https://api.airbyte.com/v1/connections?limit=5&offset=0"
          data: 
            - 
              name: "test-connection"
            - 
              connection_id: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
            - 
              sourceId: "49237019-645d-47d4-b45b-5eddf97775ce"
            - 
              destinationId: "al312fs-0ab1-4f72-9ed7-0b8fc27c5826"
            - 
              schedule: 
                scheduleType: "manual"
            - 
              status: "active"
            - 
              dataResidency: "auto"
      SourcesResponse: 
        title: "Root Type for SourcesResponse"
        description: ""
        required: 
          - "data"
        type: "object"
        properties: 
          previous: 
            type: "string"
          next: 
            type: "string"
          data: 
            type: "array"
            items: 
              $ref: "#/components/schemas/SourceResponse"
        example: 
          next: "https://api.airbyte.com/v1/sources?limit=5&offset=10"
          previous: "https://api.airbyte.com/v1/sources?limit=5&offset=0"
          data: 
            sourceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
            name: "Analytics Team Postgres"
            sourceType: "postgres"
            workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      DestinationsResponse: 
        title: "Root Type for DestinationsResponse"
        description: ""
        required: 
          - "data"
        type: "object"
        properties: 
          previous: 
            type: "string"
          next: 
            type: "string"
          data: 
            type: "array"
            items: 
              $ref: "#/components/schemas/DestinationResponse"
        example: 
          next: "https://api.airbyte.com/v1/destinations?limit=5&offset=10"
          previous: "https://api.airbyte.com/v1/destinations?limit=5&offset=0"
          data: 
            destinationId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
            name: "Analytics Team Postgres"
            destinationType: "postgres"
            workspaceId: "871d9b60-11d1-44cb-8c92-c246d53bf87e"
      WorkspacesResponse: 
        title: "Root Type for WorkspacesResponse"
        description: ""
        required: 
          - "data"
        type: "object"
        properties: 
          previous: 
            type: "string"
          next: 
            type: "string"
          data: 
            type: "array"
            items: 
              $ref: "#/components/schemas/WorkspaceResponse"
        example: 
          next: "https://api.airbyte.com/v1/workspaces?limit=5&offset=10"
          previous: "https://api.airbyte.com/v1/workspaces?limit=5&offset=0"
          data: 
            workspaceId: "18dccc91-0ab1-4f72-9ed7-0b8fc27c5826"
            name: "Acme Company"
            dataResidency: "auto"
      StreamConfiguration: 
        description: "Configurations for a single stream."
        type: "object"
        required: 
          - "name"
        properties: 
          name: 
            type: "string"
          syncMode: 
            $ref: "#/components/schemas/ConnectionSyncModeEnum"
          cursorField: 
            description: "Path to the field that will be used to determine if a record is new or modified since the last sync. This field is REQUIRED if `sync_mode` is `incremental` unless there is a default."
            type: "array"
            items: 
              type: "string"
          primaryKey: 
            description: "Paths to the fields that will be used as primary key. This field is REQUIRED if `destination_sync_mode` is `*_dedup` unless it is already supplied by the source schema."
            type: "array"
            items: 
              type: "array"
              items: 
                type: "string"
      StreamConfigurations: 
        description: "A list of configured stream options for a connection."
        type: "object"
        properties: 
          streams: 
            type: "array"
            items: 
              $ref: "#/components/schemas/StreamConfiguration"
      StreamPropertiesResponse: 
        description: "A list of stream properties."
        type: "object"
        properties: 
          streams: 
            type: "array"
            items: 
              $ref: "#/components/schemas/StreamProperties"
      StreamProperties: 
        description: "The stream properties associated with a connection."
        type: "object"
        properties: 
          streamName: 
            type: "string"
          syncModes: 
            type: "array"
            items: 
              $ref: "#/components/schemas/ConnectionSyncModeEnum"
          defaultCursorField: 
            type: "array"
            items: 
              type: "string"
          sourceDefinedCursorField: 
            type: "boolean"
          sourceDefinedPrimaryKey: 
            type: "array"
            items: 
              type: "array"
              items: 
                type: "string"
          propertyFields: 
            type: "array"
            items: 
              type: "array"
              items: 
                type: "string"
      ConnectionSyncModeEnum: 
        enum: 
          - "full_refresh_overwrite"
          - "full_refresh_append"
          - "incremental_append"
          - "incremental_deduped_history"
      ActorTypeEnum: 
        description: "Whether you're setting this override for a source or destination"
        enum: 
          - "source"
          - "destination"
      SourceConfiguration: 
        description: "The values required to configure the source."
        example: 
          user: "charles"
      DestinationConfiguration: 
        description: "The values required to configure the destination."
        example: 
          user: "charles"
    securitySchemes: 
      bearerAuth: 
        type: "http"
        scheme: "bearer"
        bearerFormat: "JWT"
  security: 
    - 
      bearerAuth: []

